site_name: Throughput Documentation
site_url: http://throughput-ec.github.io/throughput_docs
repo_url: https://github.com/throughput-ec/throughput_docs
repo_name: Github
site_author: Simon Goring

markdown_extensions:
    - toc:
        permalink: True
nav:
  - Home: index.md
  - 'Administrative':
    - Installing: admin/loading.md
  - 'Data Elements':
    - OBJECTs: nodes/objects.md
    - TYPEs: types/types.md
    - KEYWORDs: keywords/keywords.md
    - AGENTs: agents/agents.md
  - 'Data Models':
    - 'Data Models': models/data_models.md
    - Annotations: models/annotation.md


theme:
  name: mkdocs
  highlightjs: true
  hljs_languages:
    - R
    - SQL
